### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [YaziRubio/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by YaziRubio** [comment]
I think I have it, added it to the header but am unsure if it worked. 

https://splurty-yazmin-rubio.herokuapp.com/

https://github.com/YaziRubio/splurty

**Comment by Mikeysax** [comment]
Awesome job adding the meta tag! :+1:
